### ISSUE TITLE
Erro ao executar o extrato.lib

### ISSUE THREAD

**Issue by alyssonbruno** [michaelss/extrator#1]
Aparentente ele não reconhece a lib do Oracle.

```
Ocorreu um erro.
java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at br.jus.treto.extrator.Main.executeQuery(Main.java:58)
	at br.jus.treto.extrator.Main.main(Main.java:35)
```

**Comment by alyssonbruno** [comment]
Foi necessário criar um subdiretório lib e incluir o drive do oracle ojdbc6.jar.
